# options for the resources you want to expose in the api
:resources:
  :posts:
    :collection:
      :only: ["id", "title", "derived_method"]
      :include:
        :comments:
          :only: ["comment"]
      :root: true
    :get:
      :only: ["id", "title"]
      :include:
        :comments:
          :only: ["comment"]
      :root: true
    :post:
      :permitted_attributes: ["title"]
    :delete:
      :only: ["title"]
    :put:
      :permitted_attributes: ["title"]
  :comments:
    :get:
      :only: ["id", "comment"]
      :root: true
    :collection:
      :only: ["id", "comment"]
      :root: true
