# options for the resources you want to expose in the api
:resources:
  :posts:
    :get:
      :eager: 'comments'
      :json_options:
        :only: ['id', 'title']
        :include:
          :comments:
            :only: ['comment']
        :root: true
    :get_collection:
      :eager: 'comments'
      :json_options:
        :only: ['id', 'title', 'derived_method']
        :include:
          :comments:
            :only: ['id', 'comment']
        :root: true
    :post:
      :permitted_attributes: ['title']
    :put:
      :permitted_attributes: ['title']
    :delete:
  :comments:
    :get:
      :eager: 'post'
      :json_options:
        :only: ['id', 'comment']
        :root: true
    :get_collection:
      :eager: 'post'
      :json_options:
        :only: ['id', 'comment']
        :root: true
