# resources you want to expose in the api
:permitted_resources: ["products"]
# options for the resources you want to expose in the api
:resources:
  :products:
    :collection:
      :get:
        :except: ["created_at", "updated_at"]
        :root: false
    :get:
      :except: ["created_at", "updated_at"]
      :root: false
  
